# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    infinity.search:
        class: AppBundle\Utils\Search
        
    app.notifier:
        class: AppBundle\Utils\Notifier
        arguments: ["@service_container", "@doctrine"]
        
    app.mailer:
        class: AppBundle\Utils\Mailer
        arguments: ["@service_container"]
