AppBundle\Entity\Category:
    type: entity
    table: category
    indexes:
        fk_category_category1_idx:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        deleted:
            type: boolean
            nullable: false
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        tickets:
            targetEntity: Ticket
            mappedBy: category
    lifecycleCallbacks: {  }
