AppBundle\Entity\Comment:
    type: entity
    table: comment
    indexes:
        fk_comment_createdby1_idx:
            columns:
                - created_by
        fk_comment_ticket1_idx:
            columns:
                - ticket_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        text:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
    manyToOne:
        createdBy:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                created_by:
                    referencedColumnName: id
            orphanRemoval: false
        ticket:
            targetEntity: Ticket
            cascade: {  }
            inversedBy: entries
            joinColumns:
                ticket_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
