AppBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: AppBundle\Repositories\CustomerRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        activated:
            type: boolean
            nullable: false
            comment: ''
        deleted:
            type: boolean
            nullable: false
    oneToMany:
        projects:
            targetEntity: Project
            mappedBy: customer
            orphanRemoval: true
        tickets:
            targetEntity: Ticket
            mappedBy: customer
        users:
            targetEntity: User
            mappedBy: customer
            orphanRemoval: true
    lifecycleCallbacks: {  }
