AppBundle\Entity\Project:
    type: entity
    table: project
    indexes:
        fk_project_customer1_idx:
            columns:
                - customer_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        deleted:
            type: boolean
            nullable: false
    oneToMany:
        tickets:
            targetEntity: Ticket
            mappedBy: project
    manyToOne:
        customer:
            targetEntity: Customer
            cascade: {  }
            mappedBy: null
            inversedBy: projects
            joinColumns:
                customer_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
