AppBundle\Entity\Rating:
    type: entity
    table: rating
    indexes:
        fk_rating_user1_idx:
            columns:
                - user_id
        fk_rating_ticket1_idx:
            columns:
                - ticket_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        rate:
            type: smallint
            nullable: false
            length: 1
            fixed: false
            comment: ''
        solved:
            type: boolean
            nullable: false
            fixed: false
            comment: ''
        comment:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            column: created_at
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToOne:
        ticket:
            targetEntity: Ticket
            cascade: {  }
            inversedBy: rating
            joinColumn:
                name: ticket_id
                referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
