AppBundle\Entity\User:
    type: entity
    table: user
    indexes:
        fk_user_customer1_idx:
            columns:
                - customer_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        preferences:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    manyToOne:
        customer:
            targetEntity: Customer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                customer_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
